[package]
edition = "2021"
name = "net"
description = "high performance low level networking library for the Pulsar game engine"
publish = false
version = "0.1.34"

[dependencies]

# QUIC transport
quinn = "0.11.9"
