[package]
name = "ui_problems"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# UI framework
gpui.workspace = true
ui.workspace = true

# UI crates
ui_common.workspace = true
tracing = "0.1.44"
similar = "2.6"
rust-i18n.workspace = true
