[workspace]
members = [
    "crates/macros",
    "crates/engine",
    "crates/engine_backend",
    "crates/engine_state",
    "crates/engine_fs",
    "crates/ui",
    "crates/pulsar_macros",
    "crates/pulsar_std",
    "crates/multiuser_server",
    # Plugin system
    "crates/plugin_editor_api",
    "crates/plugin_manager",
    # UI component crates
    "ui-crates/ui_common",
    "ui-crates/ui_core",
    "ui-crates/ui_entry",
    "ui-crates/ui_level_editor",
    # "ui-crates/ui_daw_editor",
    "ui-crates/ui_settings",
    "ui-crates/ui_multiplayer",
    "ui-crates/ui_problems",
    "ui-crates/ui_file_manager",
    "ui-crates/ui_loading_screen",
    "ui-crates/ui_project_launcher", "ui-crates/ui_about", "ui-crates/ui_documentation", "crates/pulsar_docs",
    # Type system editors
    "ui-crates/ui_type_debugger",
    "crates/type_db",
]

default-members = ["crates/engine"]
resolver = "2"

[profile.release]
debug = true

[workspace.dependencies]
######################### TGPUI #########################
gpui = { git = "https://github.com/tristanpoland/zed", rev="2047043a00dc138e3d8127c8921c96927acea8f8", features = ["runtime_shaders", "macos-blade"] }
gpui_macros = { git = "https://github.com/tristanpoland/zed", rev="2047043a00dc138e3d8127c8921c96927acea8f8" }
reqwest_client = { git = "https://github.com/tristanpoland/zed", rev = "2047043a00dc138e3d8127c8921c96927acea8f8" }
sum_tree = { git = "https://github.com/tristanpoland/zed", rev = "2047043a00dc138e3d8127c8921c96927acea8f8" }

###################### Local WGPUI ######################
# gpui = { path = "C:/Users/redst/OneDrive/Documents/GitHub/gpui-ce/crates/gpui", features = ["runtime_shaders", "macos-blade"] }
# gpui_macros = { path = "C:/Users/redst/OneDrive/Documents/GitHub/gpui-ce/crates/gpui_macros" }
# reqwest_client = { path = "C:/Users/redst/OneDrive/Documents/GitHub/gpui-ce/crates/reqwest_client" }
# sum_tree = { path = "C:/Users/redst/OneDrive/Documents/GitHub/gpui-ce/crates/sum_tree" }

#gpui = { path = "C:/Users/redst/OneDrive/Documents/GitHub/zed/crates/gpui", features = ["runtime_shaders", "macos-blade"] }
#gpui_macros = { path = "C:/Users/redst/OneDrive/Documents/GitHub/zed/crates/gpui_macros" }
#reqwest_client = { path = "C:/Users/redst/OneDrive/Documents/GitHub/zed/crates/reqwest_client" }
#sum_tree = { path = "C:/Users/redst/OneDrive/Documents/GitHub/zed/crates/sum_tree" }

######################### WGPUI #########################
# gpui = { git = "https://github.com/Far-Beyond-Pulsar/WGPUI", rev="6f6e5f30a5306a08e9a409ad39b9a0458f0ddf01", features = ["runtime_shaders", "macos-blade"] }
# gpui_macros = { git = "https://github.com/Far-Beyond-Pulsar/WGPUI", rev="6f6e5f30a5306a08e9a409ad39b9a0458f0ddf01" }
# reqwest_client = { git = "https://github.com/Far-Beyond-Pulsar/WGPUI", rev = "6f6e5f30a5306a08e9a409ad39b9a0458f0ddf01" }
# sum_tree = { git = "https://github.com/Far-Beyond-Pulsar/WGPUI", rev = "6f6e5f30a5306a08e9a409ad39b9a0458f0ddf01" }

ui = { path = "crates/ui" }
gpui-component-macros = { path = "crates/macros" }
pulsar_std = { path = "crates/pulsar_std" }
ropey = { version = "=2.0.0-beta.1", features = ["metric_utf16", "metric_lines_lf"] }
# horizon = { git = "https://github.com/Far-Beyond-Dev/horizon" }
engine_backend = { path = "crates/engine_backend" }
engine_state = { path = "crates/engine_state" }
engine_fs = { path = "crates/engine_fs" }

# UI component crates
ui_core = { path = "ui-crates/ui_core" }
ui_entry = { path = "ui-crates/ui_entry" }
# ui_script_editor = { path = "ui-crates/ui_script_editor" }
ui_level_editor = { path = "ui-crates/ui_level_editor" }
# ui_daw_editor = { path = "ui-crates/ui_daw_editor" }
ui_settings = { path = "ui-crates/ui_settings" }
ui_multiplayer = { path = "ui-crates/ui_multiplayer" }
ui_problems = { path = "ui-crates/ui_problems" }
ui_file_manager = { path = "ui-crates/ui_file_manager" }
ui_common = { path = "ui-crates/ui_common" }
ui_loading_screen = { path = "ui-crates/ui_loading_screen" }
ui_project_launcher = { path = "ui-crates/ui_project_launcher" }
ui_about = { path = "ui-crates/ui_about" }
ui_documentation = { path = "ui-crates/ui_documentation" }
ui_types_common = { path = "ui-crates/ui_types_common" }
ui_type_debugger = { path = "ui-crates/ui_type_debugger" }
type_db = { path = "crates/type_db" }

# Plugin system
plugin_editor_api = { path = "crates/plugin_editor_api" }
plugin_manager = { path = "crates/plugin_manager" }

anyhow = "1"
log = "0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1"
schemars = "1"
smallvec = "1"
rust-i18n = "3"
raw-window-handle = "0.6.2"
winit = "0.30"
smol = "1"
tracing = "0.1.41"
notify = "7.0.0"
lsp-types = "0.97.0"
directories = "5"
itertools = "0.13"
rapier3d = { version = "*", features = [ "simd-stable" ] }
sysuri = "0.2"
urlencoding = "2.1"

[workspace.dependencies.windows]
features = ["Wdk", "Wdk_System", "Wdk_System_SystemServices", "Win32_System_Threading", "Win32_System_SystemInformation", "Win32_Graphics_Direct3D_Fxc"]
version = "0.58.0"

[workspace.lints.clippy]
almost_complete_range = "allow"
arc_with_non_send_sync = "allow"
borrowed_box = "allow"
dbg_macro = "deny"
let_underscore_future = "allow"
map_entry = "allow"
module_inception = "allow"
non_canonical_partial_ord_impl = "allow"
reversed_empty_ranges = "allow"
single_range_in_vec_init = "allow"
style = { level = "allow", priority = -1 }
todo = "deny"
type_complexity = "allow"
manual_is_multiple_of = "allow"

[profile.dev]
codegen-units = 16
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package]
resvg = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
taffy = { opt-level = 3 }
ttf-parser = { opt-level = 3 }

[workspace.metadata.typos]
files.extend-exclude = ["**/fixtures/*"]
