[package]
name = "ui_documentation"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { workspace = true }
ui = { path = "../../crates/ui" }
ui_common = { workspace = true }
pulsar_docs = { path = "../../crates/pulsar_docs" }
engine_state = { path = "../../crates/engine_state" }
regex = "1"

[lints]
workspace = true
