[package]
name = "ui_settings"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# UI framework
gpui.workspace = true
ui.workspace = true
# Engine
engine_state.workspace = true
directories = "5"
