[package]
name = "engine_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
ui_types_common = { workspace = true }
type_db = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
notify = "8.2.0"
dashmap = "6.1"
walkdir = "2.5"

[dev-dependencies]
tempfile = "3.8"
