[package]
name = "engine_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
ui_types_common = { workspace = true }
type_db = { workspace = true }
plugin_manager = { path = "../plugin_manager" }
plugin_editor_api = { path = "../plugin_editor_api" }
anyhow = { workspace = true }
tracing = { workspace = true }
serde_json = "1.0"
notify = "8.2.0"
walkdir = "2.5"
profiling = { path = "../profiling" }

[dev-dependencies]
tempfile = "3.8"
