[package]
name = "engine_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
notify = "6.1"
dashmap = "6.1"
walkdir = "2.5"
once_cell = "1.19"
ui_types_common = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
