[package]
name = "ui_common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# UI framework
gpui.workspace = true
ui.workspace = true
serde = { version = "1.0", features = ["derive"] }
rust-i18n.workspace = true
