[package]
name = "ui_multiplayer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# UI framework
gpui.workspace = true
ui.workspace = true
engine_backend.workspace = true
serde_json = "1.0"
futures = "0.3"
tracing.workspace = true
tokio = { version = "1", features = ["full"] }
similar = "2.6"
