[package]
name = "ui_loading_screen"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui.workspace = true
ui.workspace = true
engine_backend.workspace = true
engine_state.workspace = true
ui_entry.workspace = true
directories.workspace = true
tracing.workspace = true
chrono = "0.4"
