[package]
name = "ui_field_registry"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[features]
default = []
derive = ["ui_gen_macros"]

[dependencies.ui_gen_macros]
path = "../ui_gen_macros"
optional = true
